environment:
  name: "dev-qa"
  namespace: "petclinic-dev-qa"

aws:
  region: "ap-south-1"
  serviceAccountName: eks-secrets-sa

eks:
  clusterName: "devops-petclinicapp-dev-ap-south-1"

git:
  repo: "https://github.com/Subbu2025/spring-petclinic-pro.git"
  branch: "develop"

trivy:
  cache: "/var/lib/jenkins/trivy-db"

docker:
  ecrRepoUrl: "905418425077.dkr.ecr.ap-south-1.amazonaws.com/dev-qa/petclinic"
  awsRegion: "ap-south-1"

sonarqube:
  projectKey: "petclinic-dev-qa"
  serverUrl: "http://44.206.233.252:9000"

slack:
  channel: "#dev-qa"

secrets:
  awsSecrets:
    mysqlRootPasswordSecretName: "mysql-root-password"
    mysqlDatabaseSecretName: "mysql-database"
    mysqlUserSecretName: "mysql-user"
    mysqlPasswordSecretName: "mysql-password"
    sonarqubeTokenSecretName: "sonarqube-token"
    awsAccessKeyIdSecretName: "aws-access-key-id"
    awsSecretAccessKeySecretName: "aws-secret-access-key"

mysql:
  enabled: true
  auth:
    rootPassword: use-aws-secret
    username: use-aws-secret
    password: use-aws-secret
    database: "petclinic"

app:
  image:
    repository: 905418425077.dkr.ecr.ap-south-1.amazonaws.com/dev-petclinic-pro
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  env:
    MYSQL_HOST: mysql.default.svc.cluster.local
    MYSQL_DATABASE: "petclinic"        # Directly referenced value
    MYSQL_USER: "use-aws-secret"
    MYSQL_PASSWORD: "use-aws-secret"
  replicaCount: 2
  service:
    name: "petclinic-service"
    type: "LoadBalancer"  # Changed from ClusterIP to LoadBalancer
    port: 80
    targetPort: 8081
