apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-{{ .Values.environment.name }}
  namespace: {{ .Values.environment.namespace }}
data:
  # AWS and EKS configurations
  AWS_REGION: "{{ .Values.aws.region }}"
  EKS_CLUSTER_NAME: "{{ .Values.eks.clusterName }}"

  # Git configurations
  GIT_REPO: "{{ .Values.git.repo }}"
  GIT_BRANCH: "{{ .Values.git.branch }}"

  # Trivy configurations
  TRIVY_DB_CACHE: "{{ .Values.trivy.cache }}"

  # Docker ECR configurations
  ECR_REPO_URL: "{{ .Values.docker.ecrRepoUrl }}"
  AWS_REGION_ECR: "{{ .Values.docker.awsRegion }}"

   # SonarQube configurations
  SONARQUBE_PROJECT_KEY: "{{ .Values.sonarqube.projectKey }}"
  SONARQUBE_TOKEN: "{{ .Values.secrets.awsSecrets.sonarqubeTokenSecretName }}"
  SONARQUBE_URL: "http://sonarqube.yourdomain.com"  # Add this if needed


  # Slack configuration
  SLACK_CHANNEL: "{{ .Values.slack.channel }}"

  # MySQL configurations
  MYSQL_HOST: "{{ .Values.mysql.host | default 'mysql.default.svc.cluster.local' }}"
  MYSQL_DATABASE: "{{ .Values.mysql.auth.database }}"
  MYSQL_USER: "{{ .Values.mysql.auth.username }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.auth.password }}"
