apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-{{ .Values.environment.name }}
  namespace: {{ .Values.environment.namespace }}
data:
  # AWS and EKS configurations
  AWS_REGION: "{{ .Values.aws.region }}"
  EKS_CLUSTER_NAME: "{{ .Values.eks.clusterName }}"

  # Git configurations
  GIT_REPO: "{{ .Values.git.repo }}"
  GIT_BRANCH: "{{ .Values.git.branch }}"

  # Trivy configurations
  TRIVY_DB_CACHE: "{{ .Values.trivy.cache }}"

  # Docker ECR configurations
  ECR_REPO_URL: "{{ .Values.docker.ecrRepoUrl }}"
  AWS_REGION_ECR: "{{ .Values.docker.awsRegion }}"

  # SonarQube configurations (only non-sensitive data)
  SONARQUBE_PROJECT_KEY: "{{ .Values.sonarqube.projectKey }}"

  # Slack configuration
  SLACK_CHANNEL: "{{ .Values.slack.channel }}"
