apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: {{ .Values.environment.namespace }}
  labels:
    app: petclinic
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://{{ .Values.mysql.host | default 'mysql.default.svc.cluster.local' }}:3306/{{ .Values.mysql.auth.database }}"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.mysqlSecretName | default 'petclinic-secrets' }}
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.mysqlSecretName | default 'petclinic-secrets' }}
                  key: MYSQL_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: "{{ .Values.app.resources.requests.memory | default '512Mi' }}"
              cpu: "{{ .Values.app.resources.requests.cpu | default '250m' }}"
            limits:
              memory: "{{ .Values.app.resources.limits.memory | default '1Gi' }}"
              cpu: "{{ .Values.app.resources.limits.cpu | default '500m' }}"
      serviceAccountName: {{ .Values.aws.serviceAccountName | default 'eks-secrets-sa' }}
