apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  namespace: {{ .Values.environment.namespace }}
  labels:
    app: petclinic
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default 'latest' }}"
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_URL
              value: "jdbc:mysql://{{ .Values.env.MYSQL_HOST }}:3306/{{ .Values.mysql.auth.database }}"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: petclinic-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-secrets
                  key: MYSQL_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            requests:
              memory: {{ .Values.app.resources.requests.memory }}
              cpu: {{ .Values.app.resources.requests.cpu }}
            limits:
              memory: {{ .Values.app.resources.limits.memory }}
              cpu: {{ .Values.app.resources.limits.cpu }}
      serviceAccountName: {{ .Values.aws.serviceAccountName }}
