apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-secrets
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.awsSecrets.mysqlRootPasswordSecretName }}
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: {{ .Values.secrets.awsSecrets.mysqlDatabaseSecretName }}
    - secretKey: MYSQL_USER
      remoteRef:
        key: {{ .Values.secrets.awsSecrets.mysqlUserSecretName }}
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.awsSecrets.mysqlPasswordSecretName }}
