apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}                  # Service name from values
  namespace: {{ .Values.namespace }}               # Namespace from values
  labels:
    app: petclinic                                 # Common app label
    environment: {{ .Values.environment | default "development" }}  # Optional environment label
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}  # Service type from values
  ports:
    - port: {{ .Values.service.port | default 80 }}       # External port from values
      targetPort: {{ .Values.service.targetPort | default 8080 }} # Target port from values
      protocol: TCP
      name: http
  selector:
    app: petclinic
