apiVersion: v1
kind: Service
metadata:
  name: petclinic-service-prod         # Unique service name for production
  namespace: prod                      # Scoped to the 'prod' namespace
  labels:
    app: petclinic                     # Identifies the service as PetClinic
    environment: production            # Optional label for environment distinction
spec:
  type: LoadBalancer                   # Exposes the service externally
  ports:
    - port: 80                         # External port that users will access
      targetPort: 8081                 # Target port where PetClinic is running on the container
      protocol: TCP                    # Protocol for HTTP communication
      name: http                       # Name for the port, useful for monitoring
  selector:
    app: petclinic                     # Selects PetClinic pods labeled with 'app: petclinic' in the 'prod' namespace
