apiVersion: v2
name: petclinic-chart
description: A Helm chart for deploying the Spring PetClinic application on Kubernetes
type: application
version: 1.0.0                   # Version of the chart itself
appVersion: "2.5.0"              # Version of the application being deployed (e.g., PetClinic app version)

maintainers:
  - name: S. Subba Reddy
    email: subbareddysangham@example.com

sources:
  - https://github.com/spring-projects/spring-petclinic  # GitHub or other repository source for the app

keywords:
  - petclinic
  - spring
  - java
  - helm-chart
  - kubernetes

home: https://spring-petclinic.github.io  # Homepage for the app (optional)

icon: https://spring.io/images/SPR-icon.svg  # URL for an icon representing the app (optional)

dependencies:
  - name: mysql
    version: 8.0.0                      # Use the exact version of the MySQL chart available in Bitnami repo
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled            # Allows toggling the deployment of MySQL
