namespace: "petclinic-dev-qa"
environment: "dev-qa"

storage:
  storageClassName: "mysql-storage-class"
  provisioner: "kubernetes.io/aws-ebs"
  volumeType: "gp2"
  fsType: "ext4"
  reclaimPolicy: "Retain"
  allowVolumeExpansion: true
  mountOption: "debug"

persistence:
  claimName: "mysql-pvc"
  accessMode: "ReadWriteOnce"
  size: "20Gi"

image:
  tag: "8.0" # MySQL version

secrets:
  mysqlSecretName: "mysql-secrets"

mysql:
  database: "petclinic"

service:
  name: "mysql-service"  # Add this field to define the service name
  type: "ClusterIP"
  port: "3306"
  targetPort: "3306"

aws:
  region: "ap-south-1"
