apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secrets.secretStoreName | default (printf "%s-secretstore" .Release.Name) }} # Use a dynamic or specified SecretStore name
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.serviceAccountName }}
            namespace: {{ .Values.namespace }}
