apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretstore-mysql                # Unique SecretStore name for MySQL
  namespace: {{ .Values.namespace }}         # Namespace where MySQL is deployed
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}       # AWS region from values.yaml
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.serviceAccountName }} # Service account with IAM role binding
            namespace: {{ .Values.namespace }}         # Namespace of the Service Account
