apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
    environment: {{ .Values.environment | default "development" }}
data:
  MYSQL_DATABASE: {{ .Values.mysql.database }}                # Database name
  MYSQL_PORT: {{ .Values.mysql.port | default "3306" }}       # MySQL Port
  
