apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
    environment: {{ .Values.environment | default "development" }}
data:
  MYSQL_DATABASE: "{{ .Values.mysql.database | default "default_database" }}"
  MYSQL_PORT: "{{ .Values.service.port | default "3306" }}"

  
