apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval | default "1h" }} # Sync interval (default: 1 hour)
  secretStoreRef:
    name: {{ .Values.secrets.secretStoreName | default (printf "%s-secretstore" .Release.Name) }} # Dynamic SecretStore name
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-mysql-credentials
    creationPolicy: Owner # Ensures the ExternalSecret owns the Kubernetes Secret
  data:
    - secretKey: MYSQL_ROOT_PASSWORD # Kubernetes Secret key
      remoteRef:
        key: {{ .Values.secrets.awsSecretKey | default "dev-qa/petclinic-secrets" }} # AWS Secret key
        property: MYSQL_ROOT_PASSWORD # Property in the AWS Secret
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: {{ .Values.secrets.awsSecretKey | default "dev-qa/petclinic-secrets" }}
        property: MYSQL_DATABASE
    - secretKey: MYSQL_USER
      remoteRef:
        key: {{ .Values.secrets.awsSecretKey | default "dev-qa/petclinic-secrets" }}
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.awsSecretKey | default "dev-qa/petclinic-secrets" }}
        property: MYSQL_PASSWORD
