apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName | default "mysql-pvc" }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
    environment: {{ .Values.environment | default "development" }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}             # Access mode (ReadWriteOnce by default)
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}                   # Requested storage size
  storageClassName: {{ .Values.storage.storageClassName | default "mysql-storage-class" }}  # Link to StorageClass
